/**
 * Bilingual labels for the AUF form, reused from the original single-page
 * form so field wording stays identical across the rebuild.
 */
export const copy = {
  en: {
    // --- fields the 2026 guide adds ---
    nameEnFirst: "First name EN",
    nameEnSecond: "Second name EN",
    nameEnThird: "Third name EN",
    nameEnFourth: "Fourth name EN",
    placeOfBirth: "Place of birth",
    idDocument: "Copy of identity document",
    personalPhoto: "Personal photo",
    landmark: "Nearest landmark",
    monthlyIncomeAmount: "Approximate monthly income (SDG)",
    incomeProof: "Proof of income source",
    workType: "Type of work",
    workTypeEmployee: "Employee / worker / uniformed forces",
    workTypeSelfEmployed: "Self-employed",
    beneficialOwner: "Are you the beneficial owner of the account?",
    accountPurpose: "Main purpose of the account",
    usCitizen: "Do you hold United States citizenship?",
    expectedTxnNature: "Expected nature of financial transactions",
    txnSalary: "Salary",
    txnSaving: "Saving",
    txnInvestment: "Investment",
    txnInward: "Inward transfers",
    txnOutward: "Domestic transfers",
    txnOther: "Other",
    expectedTxnValue: "Average expected monthly value (SDG)",
    expectedTxnCount: "Average expected monthly number of transactions",
    signature: "Signature (as per the signature card)",
    declarationDate: "Date",
    commercialCertificate: "Income certificate",
    commercialCertificateHint: "Required because this account is commercial.",
    missingRequired: "Please complete the required fields",
    fileTooLarge: "This file is too large. The maximum size is 5 MB",
    chooseFile: "Choose a file",
    noFileChosen: "No file chosen",
    clearFile: "Remove file",
    yes: "Yes",
    no: "No",
    stepVerify: "Verify",
    stepPersonal: "Personal",
    stepContact: "Contact",
    stepWork: "Work",
    stepFinancial: "Financial",
    appName: "CBOS Customer Information Update",
    appSubtitle: "Public AUF portal",
    language: "Language",
    english: "English",
    arabic: "Arabic",
    sudapassProvider: "SudaPass",
    sudapassTitle: "Sign in with SudaPass",
    sudapassSubtitle: "Enter your national number to start the customer information form.",
    sudapassId: "National number",
    sudapassLogin: "Continue",
    sudapassDemoUsers: "Mock users",
    sudapassInvalid: "This national number is not registered in SudaPass.",
    sudapassLoaded: "Identity information loaded from SudaPass.",
    sudapassAuthenticatedAs: "Signed in as",
    sudapassUseDemo: "Use this user",
    signOut: "Sign out",
    requestStatus: "Request status",
    requestReference: "Request code",
    lookup: "Find",
    saveDraft: "Save draft",
    verifyAccount: "Verify account",
    submitRequest: "Submit request",
    previous: "Back",
    next: "Next",
    addIdentity: "Add identity",
    addIncome: "Add income source",
    addMinor: "Add minor",
    remove: "Remove",
    shared: "Shared",
    required: "Required",
    saved: "Draft saved",
    loaded: "Request loaded",
    verified: "Verification requested",
    submitted: "Request submitted",
    backendOffline: "Backend data is not available right now.",
    saveFirst: "Save the request before verification or submission.",
    namesRequired: "Arabic name and English name are required.",
    identityRequired: "At least one identity document is required before submission.",
    declarationRequired: "The declaration must be accepted before submission.",
    bankHint: "Enter the bank account reference provided by your bank.",
    existingLookup: "Existing request",
    formSection: "Form",
    reviewTitle: "Review before submitting",
    noResponse: "No request has been saved yet.",
    statusDraft: "Draft",
    statusSubmitted: "Submitted",
    statusVerified: "Verified",
    statusDone: "Done",
    statusRejected: "Rejected",
    statusCancelled: "Cancelled",
    statusUnknown: "Status",
    verification: "Verification",
    created: "Created",
    step_applicant: "Applicant",
    step_identity: "Identity",
    step_residence: "Residence",
    step_account: "Account",
    step_work: "Work",
    step_income: "Income",
    step_compliance: "PEP / FATCA",
    step_minors: "Minors",
    step_review: "Review",
    external_ref: "Request code",
    info_type: "Request type",
    name_arabic: "Full name in Arabic",
    name_english: "Full name in English",
    mother_maiden_name: "Mother's maiden name",
    gender: "Gender",
    date_of_birth: "Date of birth",
    birth_country_id: "Country of birth",
    nationality_id: "Nationality",
    marital_status: "Marital status",
    spouse_name: "Spouse name",
    mobile_personal: "Personal mobile",
    mobile_additional: "Additional mobile",
    education_level: "Education level",
    education_other: "Education, other",
    email: "Email",
    id_type: "ID type",
    id_number: "ID number",
    id_type_other: "ID type, other",
    issuance_date: "Issue date",
    expiry_date: "Expiry date",
    is_primary: "Primary document",
    res_country_state_id: "State / Wilaya",
    city_id: "City",
    area: "Area",
    district: "District",
    street: "Street",
    block: "Block",
    house_no: "House no.",
    sponsor_name: "Financial supporter name, if any",
    sponsor_business_sector: "Financial supporter work sector, if any",
    selected_bank_id: "Bank",
    bank_account_id: "Bank-account record ID",
    cif_number: "CIF number",
    business_sector: "Business sector",
    business_sector_other: "Business sector, other",
    employment_status: "Employment status",
    employment_type_specify: "Employment type, specify",
    employer_name: "Employer name",
    employer_activity: "Employer activity",
    employer_address: "Work address",
    job_title: "Job title",
    employment_date: "Employment date",
    primary_income_source: "Primary income source",
    primary_income_other: "Income source, other",
    income_other_sources: "Other income sources",
    monthly_income_range: "Monthly income range",
    salary_certificate: "Salary certificate from employer",
    annual_income_range: "Annual income range",
    annual_income_amount: "Annual income amount",
    source_funds_open_account: "Funds used to open account",
    source_funds_fund_account: "Funds used to fund account",
    expectedTransactions: "Expected transactions",
    expected_txn_deposits: "Deposits",
    expected_txn_cheques: "Cheques",
    expected_txn_inward: "Inward transfers",
    expected_txn_outward: "Outward transfers",
    source_type: "Source type",
    source_type_other: "Source type, other",
    description: "Description",
    amount: "Amount",
    pep_is_pep: "Politically exposed person",
    pep_position: "PEP position / role",
    pep_relative_pep: "Relative of a PEP",
    pep_relative_details: "PEP relative details",
    fatca_us_citizen: "US citizen",
    fatca_born_usa: "Born in the USA",
    fatca_dual_citizenship: "Dual citizenship including US",
    fatca_other_citizenship: "Other citizenship",
    fatca_other_citizenship_specify: "Other citizenship, specify",
    fatca_us_green_card: "US Green Card",
    fatca_us_passport: "US passport",
    fatca_us_mailing_address: "US mailing address / PO box",
    fatca_us_proxy_authorized: "US proxy authorized on account",
    fatca_us_standing_order_out: "Standing order to the USA",
    fatca_us_standing_order_in: "Standing order from the USA",
    fatca_us_stay_183days: "Stayed in USA over 183 days",
    fatca_stay_reason: "US stay reason",
    fatca_stay_reason_specify: "US stay reason, specify",
    declaration_accepted: "I confirm the information is accurate and I accept the declaration.",
    minor_name: "Minor name",
    minor_dob: "Minor date of birth",
    minor_id_type: "Minor ID type",
    minor_id_number: "Minor ID number",
    guardian_cif: "Guardian CIF",
    guardian_account_no: "Guardian account no.",
    selectPlaceholder: "Select",
    optional: "Optional",
  },
  ar: {
    // --- fields the 2026 guide adds ---
    nameEnFirst: "الاسم الأول EN",
    nameEnSecond: "الاسم الثاني EN",
    nameEnThird: "الاسم الثالث EN",
    nameEnFourth: "الاسم الرابع EN",
    placeOfBirth: "مكان الميلاد",
    idDocument: "صورة من مستند الهوية",
    personalPhoto: "الصورة الشخصية",
    landmark: "أقرب معلم بارز",
    monthlyIncomeAmount: "الدخل الشهري التقريبي (جنيه)",
    incomeProof: "مستند إثبات مصدر الدخل",
    workType: "نوع العمل",
    workTypeEmployee: "موظفين/عمال/قوات نظامية",
    workTypeSelfEmployed: "أعمال حرة",
    beneficialOwner: "هل أنت تمثل المستفيد الحقيقي من الحساب؟",
    accountPurpose: "ما هو الغرض الأساسي من الحساب",
    usCitizen: "هل تحمل الجنسية الأمريكية؟",
    expectedTxnNature: "ما هي طبيعة العمليات المالية المتوقعة",
    txnSalary: "راتب",
    txnSaving: "ادخار",
    txnInvestment: "استثمار",
    txnInward: "تحويلات من الخارج",
    txnOutward: "تحويلات داخلية",
    txnOther: "أخرى",
    expectedTxnValue: "متوسط قيمة العمليات المتوقعة شهرياً (بالجنيه)",
    expectedTxnCount: "متوسط عدد الحركات المالية المتوقعة شهرياً",
    signature: "التوقيع (كما في نموذج التوقيعات)",
    declarationDate: "التاريخ",
    commercialCertificate: "شهادة دخل",
    commercialCertificateHint: "مطلوبة لأن هذا الحساب تجاري.",
    missingRequired: "يرجى تعبئة الحقول المطلوبة",
    fileTooLarge: "حجم الملف كبير جداً. الحد الأقصى 5 ميجابايت",
    chooseFile: "اختر ملفاً",
    noFileChosen: "لم يتم اختيار ملف",
    clearFile: "إزالة الملف",
    yes: "نعم",
    no: "لا",
    stepVerify: "تحقق",
    stepPersonal: "شخصية",
    stepContact: "اتصال",
    stepWork: "العمل",
    stepFinancial: "مالية",
    appName: "تحديث بيانات العملاء - بنك السودان المركزي",
    appSubtitle: "بوابة عامة لنموذج AUF",
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    sudapassProvider: "سوداباس",
    sudapassTitle: "تسجيل الدخول عبر سوداباس",
    sudapassSubtitle: "أدخل الرقم الوطني لبدء نموذج تحديث بيانات العميل.",
    sudapassId: "الرقم الوطني",
    sudapassLogin: "متابعة",
    sudapassDemoUsers: "مستخدمون تجريبيون",
    sudapassInvalid: "الرقم الوطني غير مسجل في سوداباس.",
    sudapassLoaded: "تم تحميل بيانات الهوية من سوداباس.",
    sudapassAuthenticatedAs: "تم تسجيل الدخول باسم",
    sudapassUseDemo: "استخدم هذا المستخدم",
    signOut: "تسجيل الخروج",
    requestStatus: "حالة الطلب",
    requestReference: "رمز الطلب",
    lookup: "بحث",
    saveDraft: "حفظ مسودة",
    verifyAccount: "تحقق من الحساب",
    submitRequest: "إرسال الطلب",
    previous: "رجوع",
    next: "التالي",
    addIdentity: "إضافة هوية",
    addIncome: "إضافة مصدر دخل",
    addMinor: "إضافة قاصر",
    remove: "حذف",
    shared: "مشترك",
    required: "مطلوب",
    saved: "تم حفظ المسودة",
    loaded: "تم تحميل الطلب",
    verified: "تم طلب التحقق",
    submitted: "تم إرسال الطلب",
    backendOffline: "بيانات الخادم غير متاحة الآن.",
    saveFirst: "احفظ الطلب قبل التحقق أو الإرسال.",
    namesRequired: "الاسم بالعربية والاسم بالإنجليزية مطلوبان.",
    identityRequired: "يجب إدخال مستند هوية واحد على الأقل قبل الإرسال.",
    declarationRequired: "يجب قبول الإقرار قبل الإرسال.",
    bankHint: "أدخل مرجع الحساب الذي زودك به البنك.",
    existingLookup: "طلب سابق",
    formSection: "النموذج",
    reviewTitle: "مراجعة قبل الإرسال",
    noResponse: "لم يتم حفظ طلب حتى الآن.",
    statusDraft: "مسودة",
    statusSubmitted: "مرسل",
    statusVerified: "تم التحقق",
    statusDone: "مكتمل",
    statusRejected: "مرفوض",
    statusCancelled: "ملغي",
    statusUnknown: "الحالة",
    verification: "التحقق",
    created: "تاريخ الإنشاء",
    step_applicant: "مقدم الطلب",
    step_identity: "الهوية",
    step_residence: "السكن",
    step_account: "الحساب",
    step_work: "العمل",
    step_income: "الدخل",
    step_compliance: "PEP / FATCA",
    step_minors: "القصر",
    step_review: "المراجعة",
    external_ref: "رمز الطلب",
    info_type: "نوع الطلب",
    name_arabic: "الاسم الكامل بالعربية",
    name_english: "الاسم الكامل بالإنجليزية",
    mother_maiden_name: "اسم الأم",
    gender: "الجنس",
    date_of_birth: "تاريخ الميلاد",
    birth_country_id: "بلد الميلاد",
    nationality_id: "الجنسية",
    marital_status: "الحالة الاجتماعية",
    spouse_name: "اسم الزوج/الزوجة",
    mobile_personal: "رقم الهاتف الشخصي",
    mobile_additional: "رقم هاتف إضافي",
    education_level: "المستوى التعليمي",
    education_other: "تعليم آخر",
    email: "البريد الإلكتروني",
    id_type: "نوع الهوية",
    id_number: "رقم الهوية",
    id_type_other: "نوع هوية آخر",
    issuance_date: "تاريخ الإصدار",
    expiry_date: "تاريخ الانتهاء",
    is_primary: "مستند أساسي",
    res_country_state_id: "الولاية",
    city_id: "المدينة",
    area: "المنطقة",
    district: "المحلية / الحي",
    street: "الشارع",
    block: "المربع",
    house_no: "رقم المنزل",
    sponsor_name: "اسم المعيل إن وجد",
    sponsor_business_sector: "قطاع عمل المعيل إن وجد",
    selected_bank_id: "البنك",
    bank_account_id: "رقم سجل الحساب البنكي",
    cif_number: "رقم CIF",
    business_sector: "قطاع العمل",
    business_sector_other: "قطاع عمل آخر",
    employment_status: "حالة العمل",
    employment_type_specify: "تفاصيل حالة العمل",
    employer_name: "اسم جهة العمل",
    employer_activity: "نشاط جهة العمل",
    employer_address: "عنوان العمل",
    job_title: "المسمى الوظيفي",
    employment_date: "تاريخ التوظيف",
    primary_income_source: "مصدر الدخل الرئيسي",
    primary_income_other: "مصدر دخل آخر",
    income_other_sources: "مصادر دخل إضافية",
    monthly_income_range: "نطاق الدخل الشهري",
    salary_certificate: "شهادة راتب من جهة العمل",
    annual_income_range: "نطاق الدخل السنوي",
    annual_income_amount: "مبلغ الدخل السنوي",
    source_funds_open_account: "مصدر أموال فتح الحساب",
    source_funds_fund_account: "مصدر تمويل الحساب",
    expectedTransactions: "المعاملات المتوقعة",
    expected_txn_deposits: "إيداعات",
    expected_txn_cheques: "شيكات",
    expected_txn_inward: "تحويلات واردة",
    expected_txn_outward: "تحويلات صادرة",
    source_type: "نوع المصدر",
    source_type_other: "نوع مصدر آخر",
    description: "الوصف",
    amount: "المبلغ",
    pep_is_pep: "شخصية سياسية ممثلة للمخاطر",
    pep_position: "المنصب / الدور",
    pep_relative_pep: "قريب لشخصية سياسية",
    pep_relative_details: "تفاصيل القرابة",
    fatca_us_citizen: "مواطن أمريكي",
    fatca_born_usa: "مولود في الولايات المتحدة",
    fatca_dual_citizenship: "جنسية مزدوجة تشمل الأمريكية",
    fatca_other_citizenship: "جنسية أخرى",
    fatca_other_citizenship_specify: "تحديد الجنسية الأخرى",
    fatca_us_green_card: "بطاقة خضراء أمريكية",
    fatca_us_passport: "جواز سفر أمريكي",
    fatca_us_mailing_address: "عنوان بريدي أمريكي",
    fatca_us_proxy_authorized: "وكيل أمريكي مفوض على الحساب",
    fatca_us_standing_order_out: "أمر تحويل دائم إلى الولايات المتحدة",
    fatca_us_standing_order_in: "أمر تحويل دائم من الولايات المتحدة",
    fatca_us_stay_183days: "الإقامة في أمريكا أكثر من 183 يوما",
    fatca_stay_reason: "سبب الإقامة في أمريكا",
    fatca_stay_reason_specify: "تحديد سبب الإقامة",
    declaration_accepted: "أؤكد صحة البيانات وأوافق على الإقرار.",
    minor_name: "اسم القاصر",
    minor_dob: "تاريخ ميلاد القاصر",
    minor_id_type: "نوع هوية القاصر",
    minor_id_number: "رقم هوية القاصر",
    guardian_cif: "رقم CIF للولي",
    guardian_account_no: "رقم حساب الولي",
    selectPlaceholder: "اختر",
    optional: "اختياري",
  },
} as const;

/** Label values widened to string so either language satisfies the type. */
export type AufCopy = { [K in keyof (typeof copy)["ar"]]: string };
