import type { LandingCopy, Language } from "./types";

export const landingCopy: Record<Language, LandingCopy> = {
  en: {
    platformName: "Central Verification Platform",
    platformTagline: "For updating customer data",
    navAbout: "About the platform",
    navHelp: "Help",
    language: "Language",
    english: "English",
    arabic: "Arabic",
    heroTitle: "Update your data once for all banks",
    heroSubtitle:
      "A secure, centralized platform that lets you update your personal and financial data at every participating bank in a few simple steps.",
    featureSecureTitle: "Safe & protected",
    featureSecureDesc: "High-grade protection for your data under the best standards",
    featureTimeTitle: "Saves your time",
    featureTimeDesc: "One update instead of repeating the process at every bank",
    featureBankTitle: "Approved by banks",
    featureBankDesc: "Your data is updated at every participating bank",
    welcomeGreeting: "Welcome",
    welcomeIntro: "To get started updating your data at the banks, please sign in with SudaPass.",
    trustBadges: "Secure  •  Fast  •  Trusted",
    privacyNote: "SudaPass is used only to verify your identity. Your data is never shared without your consent.",
    noAccount: "Don't have a SudaPass account?",
    createAccount: "Create a new account",
    sudapassTitle: "Sign in with SudaPass",
    sudapassLogin: "Continue",
    howItWorks: "How the platform works",
    step1Title: "Sign in with SudaPass",
    step1Desc: "Verify your identity securely and quickly via SudaPass",
    step2Title: "Update your data",
    step2Desc: "Review your data and update it in one simple form",
    step3Title: "Choose banks & accounts",
    step3Desc: "Pick the banks and branches and add your accounts to update",
    step4Title: "Submit & track status",
    step4Desc: "Send your request and track its status from one place",
    footerRights: "© 2026 Central Verification Platform for updating customer data. All rights reserved.",
    footerTerms: "Terms & Conditions",
    footerPrivacy: "Privacy Policy",
  },
  ar: {
    platformName: "منصة التحقق المركزي",
    platformTagline: "لتحديث بيانات العملاء",
    navAbout: "عن المنصة",
    navHelp: "مساعدة",
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    heroTitle: "تحديث بياناتك مرة واحدة لجميع البنوك",
    heroSubtitle:
      "منصة مركزية وآمنة تتيح لك تحديث بياناتك الشخصية والمالية لدى جميع البنوك المشاركة بخطوات بسيطة وسهلة.",
    featureSecureTitle: "آمن ومحمي",
    featureSecureDesc: "حماية عالية لبياناتك وفق أفضل المعايير",
    featureTimeTitle: "يوفر وقتك",
    featureTimeDesc: "تحديث واحد يغنيك عن تكرار الإجراءات",
    featureBankTitle: "معتمد من البنوك",
    featureBankDesc: "تحديث بياناتك لدى جميع البنوك المشاركة",
    welcomeGreeting: "مرحباً بك",
    welcomeIntro: "للبدء في تحديث بياناتك لدى البنوك يرجى تسجيل الدخول عبر سوداباس",
    trustBadges: "آمن  •  سريع  •  موثوق",
    privacyNote: "يتم استخدام سوداباس للتحقق من هويتك فقط، ولا تتم مشاركة بياناتك بدون موافقتك.",
    noAccount: "ليس لديك حساب في سوداباس؟",
    createAccount: "إنشاء حساب جديد",
    sudapassTitle: "تسجيل الدخول عبر سوداباس",
    sudapassLogin: "متابعة",
    howItWorks: "كيفية عمل المنصة",
    step1Title: "تسجيل الدخول عبر سوداباس",
    step1Desc: "تحقق من هويتك بطريقة آمنة وسريعة عبر سوداباس",
    step2Title: "تحديث بياناتك",
    step2Desc: "راجع بياناتك وقم بتحديثها في نموذج واحد مبسط",
    step3Title: "اختيار البنوك والحسابات",
    step3Desc: "اختر البنوك وفروعها وأضف حساباتك لتحديثها",
    step4Title: "إرسال الطلب ومتابعة الحالة",
    step4Desc: "أرسل طلبك وتابع حالة المراجعة لكل بنك من مكان واحد",
    footerRights: "جميع الحقوق محفوظة © 2026 منصة التحقق المركزي لتحديث بيانات العملاء",
    footerTerms: "الشروط والأحكام",
    footerPrivacy: "سياسة الخصوصية",
  },
};
