import type { LandingCopy, Language } from "./types";

export const landingCopy: Record<Language, LandingCopy> = {
  en: {
    platformName: "Omdurman National Bank Platform",
    platformTagline: "For updating customer data",
    language: "Language",
    english: "English",
    arabic: "Arabic",
    heroTitle: "Update your data with Omdurman National Bank",
    heroLogoAlt: "Omdurman National Bank",
    heroSubtitle:
      "A secure platform that lets you update your personal and financial data at Omdurman National Bank in a few simple steps.",
    featureSecureTitle: "Safe & protected",
    featureSecureDesc: "High-grade protection for your data under the best standards",
    featureTimeTitle: "Saves your time",
    featureTimeDesc: "One simple update instead of a branch visit",
    featureBankTitle: "Approved by the bank",
    featureBankDesc: "Your data is updated directly with Omdurman National Bank",
    welcomeGreeting: "Welcome",
    welcomeIntro: "To get started updating your data at the banks, please sign in with SudaPass.",
    trustBadges: "Secure  •  Fast  •  Trusted",
    privacyNote: "SudaPass is used only to verify your identity. Your data is never shared without your consent.",
    sudapassTitle: "Sign in with SudaPass",
    sudapassLogin: "Continue",
    howItWorks: "How the platform works",
    step1Title: "Sign in with SudaPass",
    step1Desc: "Verify your identity securely and quickly via SudaPass",
    step2Title: "Update your data",
    step2Desc: "Review your data and update it in one simple form",
    step3Title: "Choose branch & accounts",
    step3Desc: "Pick your branch and add your accounts to update",
    step4Title: "Submit & track status",
    step4Desc: "Send your request and follow its review with Omdurman National Bank",
    footerRights: "© 2026 Omdurman National Bank Platform for updating customer data. All rights reserved.",
  },
  ar: {
    platformName: "منصة بنك أم درمان الوطني",
    platformTagline: "لتحديث بيانات العملاء",
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    heroTitle: "حدّث بياناتك لدى بنك أم درمان الوطني",
    heroLogoAlt: "بنك أم درمان الوطني",
    heroSubtitle:
      "منصة آمنة تتيح لك تحديث بياناتك الشخصية والمالية لدى بنك أم درمان الوطني بخطوات بسيطة وسهلة.",
    featureSecureTitle: "آمن ومحمي",
    featureSecureDesc: "حماية عالية لبياناتك وفق أفضل المعايير",
    featureTimeTitle: "يوفر وقتك",
    featureTimeDesc: "تحديث واحد يغنيك عن زيارة الفرع",
    featureBankTitle: "معتمد من البنك",
    featureBankDesc: "تحديث بياناتك مباشرة لدى بنك أم درمان الوطني",
    welcomeGreeting: "مرحباً بك",
    welcomeIntro: "للبدء في تحديث بياناتك لدى بنك أم درمان الوطني يرجى تسجيل الدخول عبر سوداباس",
    trustBadges: "آمن  •  سريع  •  موثوق",
    privacyNote: "يتم استخدام سوداباس للتحقق من هويتك فقط، ولا تتم مشاركة بياناتك بدون موافقتك.",
    sudapassTitle: "تسجيل الدخول عبر سوداباس",
    sudapassLogin: "متابعة",
    howItWorks: "كيفية عمل المنصة",
    step1Title: "تسجيل الدخول عبر سوداباس",
    step1Desc: "تحقق من هويتك بطريقة آمنة وسريعة عبر سوداباس",
    step2Title: "تحديث بياناتك",
    step2Desc: "راجع بياناتك وقم بتحديثها في نموذج واحد مبسط",
    step3Title: "اختيار الفرع والحسابات",
    step3Desc: "اختر فرعك وأضف حساباتك لتحديثها",
    step4Title: "إرسال الطلب ومتابعة الحالة",
    step4Desc: "أرسل طلبك وتابع حالة المراجعة لدى بنك أم درمان الوطني",
    footerRights: "جميع الحقوق محفوظة © 2026 منصة بنك أم درمان الوطني لتحديث بيانات العملاء",
  },
};
