export type Language = "en" | "ar";

export type LandingCopy = {
  platformName: string;
  platformTagline: string;
  navAbout: string;
  navHelp: string;
  language: string;
  english: string;
  arabic: string;
  heroTitle: string;
  heroSubtitle: string;
  featureSecureTitle: string;
  featureSecureDesc: string;
  featureTimeTitle: string;
  featureTimeDesc: string;
  featureBankTitle: string;
  featureBankDesc: string;
  welcomeGreeting: string;
  welcomeIntro: string;
  trustBadges: string;
  privacyNote: string;
  noAccount: string;
  createAccount: string;
  sudapassTitle: string;
  sudapassLogin: string;
  howItWorks: string;
  step1Title: string;
  step1Desc: string;
  step2Title: string;
  step2Desc: string;
  step3Title: string;
  step3Desc: string;
  step4Title: string;
  step4Desc: string;
  footerRights: string;
  footerTerms: string;
  footerPrivacy: string;
};
