import type { Language, RequestCopy } from "./types";

export const requestCopy: Record<Language, RequestCopy> = {
  ar: {
    pageTitle: "تفاصيل طلب التحديث",
    pageSubtitle: "متابعة حالة طلبك لدى جميع البنوك",
    downloadPdf: "تحميل PDF",
    print: "طباعة",
    referenceLabel: "رقم طلب التحديث",
    createdLabel: "تاريخ إنشاء الطلب",
    copyReference: "نسخ رقم الطلب",
    submittedNotice: "تم إرسال طلبك بنجاح إلى البنوك المختارة. سيتم إشعارك عند اعتماد جميع البنوك.",
    bankReviewTitle: "حالة المراجعة لدى البنوك",
    colBank: "البنك",
    colBranch: "الفرع",
    colAccount: "رقم الحساب",
    colStatus: "الحالة",
    colLastUpdate: "آخر تحديث",
    colAction: "الإجراء",
    viewDetails: "عرض التفاصيل",
    actionNotice: "يرجى مراجعة الإجراء المطلوب من قبل البنك لتجنب تأخير اعتماد الطلب.",
    summaryTitle: "ملخص الطلب",
    bankCountLabel: "عدد البنوك",
    accountCountLabel: "عدد الحسابات",
    requestTypeLabel: "نوع الطلب",
    overallStatusLabel: "الحالة العامة",
    banksUnit: "بنوك",
    accountsUnit: "حسابات",
    updatedFieldsTitle: "البيانات التي تم تحديثها",
    helpTitle: "تحتاج مساعدة؟",
    helpBody: "فريق الدعم متاح لمساعدتك",
    liveChat: "محادثة مباشرة",
    status: {
      approved: "معتمد",
      under_review: "قيد المراجعة",
      action_required: "يحتاج إجراء",
    },
  },
  en: {
    pageTitle: "Update request details",
    pageSubtitle: "Track your request status across all banks",
    downloadPdf: "Download PDF",
    print: "Print",
    referenceLabel: "Update request number",
    createdLabel: "Request created on",
    copyReference: "Copy request number",
    submittedNotice:
      "Your request was sent successfully to the selected banks. You will be notified once all banks approve it.",
    bankReviewTitle: "Review status across banks",
    colBank: "Bank",
    colBranch: "Branch",
    colAccount: "Account no.",
    colStatus: "Status",
    colLastUpdate: "Last update",
    colAction: "Action",
    viewDetails: "View details",
    actionNotice: "Please review the action requested by the bank to avoid delaying approval.",
    summaryTitle: "Request summary",
    bankCountLabel: "Banks",
    accountCountLabel: "Accounts",
    requestTypeLabel: "Request type",
    overallStatusLabel: "Overall status",
    banksUnit: "banks",
    accountsUnit: "accounts",
    updatedFieldsTitle: "Updated information",
    helpTitle: "Need help?",
    helpBody: "Our support team is here to help",
    liveChat: "Live chat",
    status: {
      approved: "Approved",
      under_review: "Under review",
      action_required: "Action required",
    },
  },
};
